### ISSUE TITLE
Improve the visualization of the data in the queue, and clearly display what each node color represents

### ISSUE THREAD

**Issue by ash-k121** [sakeel-103/DFS-BFS-Graph-Travers#1]
The visualization could be enhanced by better illustrating the nodes being pushed into or popped from the queue, as well as clearly showing the movement between nodes during BFS and DFS traversal.
![image](https://github.com/user-attachments/assets/78adea3c-5083-4e5a-8be2-d89e53ee1f4b)

**Comment by sakeel-103** [comment]
I have used three colors during the traversal: red to examine the connection path, blue to show the next path to traverse, and yellow for the current node.
