### ISSUE TITLE
Add Dijkstra's Algorithm Endpoint to Server

### ISSUE THREAD

**Issue by muskan171105** [sakeel-103/DFS-BFS-Graph-Travers#110]
Implement an endpoint for Dijkstra's algorithm in server.js to handle weighted graph data. The new endpoint should accept a JSON object containing the graph and the starting node. It will return the shortest paths from the starting node to all other nodes.

Note: Please assign me this issue. I am a contributor at hacktoberfest and gssoc ext'24.

I have the PR ready. Just assign me this issue and I will push it

**Comment by sakeel-103** [comment]
@muskan171105 
great !! Work on it.
