### ISSUE TITLE
Issue Title: "Enhance Footer Section"

### ISSUE THREAD

**Issue by AswaniBolisetti** [sakeel-103/DFS-BFS-Graph-Travers#119]
@sakeel-103 
Issue Description: I would like to enhance the footer section by improving its design, adding relevant links, updating the contact details, and including social media icons. The goal is to make the footer more informative and visually appealing, improving user experience.

Please assign this issue to me under the labels: level2, gssoc-ext, and hacktoberfest-accepted.

**Comment by sakeel-103** [comment]
@AswaniBolisetti 
Sure !!
