### ISSUE TITLE
Issue Title: "Implement Smooth Scroll for Navbar Items"

### ISSUE THREAD

**Issue by AswaniBolisetti** [sakeel-103/DFS-BFS-Graph-Travers#121]
@sakeel-103 
Issue Description: I would like to implement smooth scroll functionality for the items in the navbar. This will ensure that when users click on a navbar item, the page smoothly scrolls to the corresponding section, providing a more seamless and user-friendly navigation experience.

Please assign this issue to me under the labels: level2, gssoc-ext, and hacktoberfest-accepted.

**Comment by sakeel-103** [comment]
@AswaniBolisetti 
Apologize for this, during the merge process, I'll assign a level based on the work or implementation. Plz work on this issue.
