### ISSUE TITLE
Feature Request: Add Referral Program Feature

### ISSUE THREAD

**Issue by muskan171105** [sakeel-103/DFS-BFS-Graph-Travers#129]
Implement a referral program feature in the DonorConnect app to incentivize users for referring new members. The feature allows users to enter a referral code during the sign-up process, which rewards the referrer upon successful registration of the referred user.

Please assign me this issue under GSSoC and Hacktoberfest

**Comment by sakeel-103** [comment]
@muskan171105 
Why you closed this issue ?
