### ISSUE TITLE
Improvement in the login page

### ISSUE THREAD

**Issue by MetiUmashri** [sakeel-103/DFS-BFS-Graph-Travers#13]
This page looks quite basic. In the below provided image i would like to work and improvise the issue as well. Equally I even look forward to add a loader after successful login before redirecting to the home page. Kindly assign this iusse to me.
<img width="960" alt="image" src="https://github.com/user-attachments/assets/8f3a39bd-ae29-47e2-9a97-c375caa3e5ec">

**Comment by MetiUmashri** [comment]
@sakeel-103 i would like to work on this enhancemet part of the website

**Comment by harish08102004** [comment]
Hey @sakeel-103 I can work on improving this.

**Comment by sakeel-103** [comment]
@harish08102004 
@MetiUmashri 
Sorry to inform, this issue has been solved by another person in another issue bcz of long time to being assigned.
@harish08102004 
Plz work on another issue, infect raise own issue.
