### ISSUE TITLE
Do we need landing home page?

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#136]
I don't think we need a landing page. At the server's start, it should directly open the login page. 

![g1](https://github.com/user-attachments/assets/0b4bd256-cc9f-4ef5-ab75-7fc544f99634)

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
No, I needed a landing page when the server started. My idea was similar to what we have right now. 
Apologies for the confusion. 
Please find the correct issue.
So, I'm closing this issue.

**Comment by mehul-m-prajapati** [comment]
@sakeel-103 : okay, thanks for your review.
