### ISSUE TITLE
Add mini chatbot to the website 

### ISSUE THREAD

**Issue by say-het** [sakeel-103/DFS-BFS-Graph-Travers#139]
Hey @sakeel-103 I have a great Idea.

 - Adding a mini AI based chatbot to website.

I am already working on this, please assign me this under gssoc-ext so I can raise a PR.

Little about me: I am an experienced contributor as I have successfully completed GSSoC-2024, Hacktoberfest-2020 and Hacktoberfest-2023.

Something like this.

![image](https://github.com/user-attachments/assets/9f34a185-e7f8-4cbb-bbef-c470204532e8)

**Comment by sakeel-103** [comment]
@say-het 
Sorry to say, this issue has already been assigned. Please check it.
#118
