### ISSUE TITLE
 Add "Remember Me" Checkbox to Login Form

### ISSUE THREAD

**Issue by 09viv** [sakeel-103/DFS-BFS-Graph-Travers#154]
Hi @sakeel-103 

Description:
This pull request adds a "Remember Me" checkbox to the login form. When users select this option, their login credentials will be remembered for future visits, allowing them to remain logged in for a longer period. This feature will improve the user experience by providing convenience, especially for frequent users who prefer not to re-enter their login details every time.

The feature includes:
A "Remember Me" checkbox in the login form.
Improved user convenience by allowing automatic login without re-entering credentials for returning users.

Please assign me this issue under GSSOC and Hacktoberfest

**Comment by sakeel-103** [comment]
@09viv 
Customer support chatbox functionality feature has already been assigned, but this feature you only want to add in the login function then its fine go ahead.
Remember - Chatbox feature has already been assigned.
#118 check this issue, if this feature is same to that one then work according to them.
