### ISSUE TITLE
update Readme.md to include the custom graph feature usage

### ISSUE THREAD

**Issue by LifeHashed** [sakeel-103/DFS-BFS-Graph-Travers#16]
Update the readme.md

**Comment by sakeel-103** [comment]
readme file update has already been assigned, but you can add only this custom graph update.

**Comment by LifeHashed** [comment]
Sure @sakeel-103

**Comment by LifeHashed** [comment]
@sakeel-103 updated readme and raised issue to implement auto scrolling on hitting create custom graph button
