### ISSUE TITLE
Adding login/signup button in navbar

### ISSUE THREAD

**Issue by Sourabh782** [sakeel-103/DFS-BFS-Graph-Travers#191]
![image](https://github.com/user-attachments/assets/0f084caf-6a34-443a-a9a0-2d97e93768e3)

adding login/signup button at navbar for easier access

**Comment by sakeel-103** [comment]
@Sourabh782 
not to add login/signup button in the navbar of the landing page in fact improve the theme of the login/signup page according to the theme of landing page

**Comment by Sourabh782** [comment]
Sure @sakeel-103 👍👍

**Comment by Sourabh782** [comment]
@sakeel-103 can you check this? 

![image](https://github.com/user-attachments/assets/7b4de68a-7173-4435-b320-467a2473830e)

**Comment by Sourabh782** [comment]
> @sakeel-103 can you check this?
> 
> ![image](https://private-user-images.githubusercontent.com/103349890/378185680-7b4de68a-7173-4435-b320-467a2473830e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODk4NTksIm5iZiI6MTcyOTQ4OTU1OSwicGF0aCI6Ii8xMDMzNDk4OTAvMzc4MTg1NjgwLTdiNGRlNjhhLTcxNzMtNDQzNS1iMzIwLTQ2N2EyNDczODMwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwNTQ1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjE4OTBiZTUxNWEyY2EzYjIwOWRlZWEyMjA0N2VjNDVkMjUwNWEwNmEzMDZlNjkyZDFkOGE3NmU5Y2E3NDVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yLnqT3aMrS5JkqwtNPpX6hrY3VflEHlaE0rNJ8Tsgqw)
> 
> if this looks good i will implement signup page in same design

@sakeel-103 any response?

**Comment by Sourabh782** [comment]
![Screenshot 2024-10-21 161234](https://github.com/user-attachments/assets/fc81c7ec-286e-4f4e-9a0e-2167e099b773)

![Screenshot 2024-10-21 161223](https://github.com/user-attachments/assets/ee80b52e-d6c4-4317-b18d-a9a8eb2608c0)
