### ISSUE TITLE
Adding FAQ page

### ISSUE THREAD

**Issue by 09viv** [sakeel-103/DFS-BFS-Graph-Travers#211]
Hi  @sakeel-103 
Description:
This PR will add FAQ page to address common user questions. This task involves creating and linking a dedicated FAQ page where users can find answers related to the visualizer and the graph algorithms (e.g., BFS, DFS, Dijkstra).

Features:
New FAQ Page: A responsive FAQ page built using Bootstrap to handle common questions about the visualizer and graph algorithms.
Collapsible Sections: Accordion-style collapsible sections for each question to improve readability and navigation.
Navigation Integration: A link to the FAQ page added to the website's header or footer for easy access.

Please assign me this issue under GSSOC and Hacktoberfest

**Comment by sakeel-103** [comment]
@09viv 
Sorry to say, this section has already been added, if you want to work then you can improve the section or add some more question there.
