### ISSUE TITLE
Big canvas space having blank content on landing page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#220]
![c1](https://github.com/user-attachments/assets/e4db4f6f-0b8f-47b8-a7d6-4b45afbe70fb)

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
Ok, please tell the implementations which you want to add here.

**Comment by mehul-m-prajapati** [comment]
> @mehul-m-prajapati Ok, please tell the implementations which you want to add here.

@sakeel-103 
- There a header and js code under canvas which renders nothing. Maybe we should remove that part of code.
