### ISSUE TITLE
Add contact us page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#221]
- A page where users can submit feedback, questions, or suggestions regarding the project.

---
![g1](https://github.com/user-attachments/assets/5ce9e74c-7a79-45d6-9d45-ecc60ba97e7c)

--
- Also, add hyper link of contact us page on landing page which is currently blank.

**Comment by Jashwanth-rit** [comment]
Okay 👍
