### ISSUE TITLE
ADD: Feature to enable auto-scroll on hitting create custom graph button

### ISSUE THREAD

**Issue by LifeHashed** [sakeel-103/DFS-BFS-Graph-Travers#23]
On clicking the button "Create Custom Graph" the page will auto scroll down to the canvas area where the graph is being drawn

**Comment by sakeel-103** [comment]
please add details in the above field

**Comment by LifeHashed** [comment]
@sakeel-103 
Added description

**Comment by LifeHashed** [comment]
This feature has been added
