### ISSUE TITLE
[Bug]: Dropdown closing problem in main-index-page

### ISSUE THREAD

**Issue by Jashwanth-rit** [sakeel-103/DFS-BFS-Graph-Travers#236]
description: 

unable to close dropdown , when we click outside the drop down in main-index-page,

steps to reproduce:

1. go to home page 
2. login 
3. click on corner profile kind of image 

![Screenshot 2024-10-15 230124](https://github.com/user-attachments/assets/c51f0499-48be-489c-a65f-02e1286978e5)
4. click outside of dropdown , not closing .

@sakeel-103 add gssoc and hacktoberfest tag and let us to contribute on this issue.

**Comment by sakeel-103** [comment]
@Jashwanth-rit 
I apologize for this confusion, this issue has been resolved earlier and was closed that's why I didn't recognize it and assigned you. 
Please find other issue.

**Comment by mehul-m-prajapati** [comment]
don't worry @sakeel-103
I raised issue #221  and PR was done by @Jashwanth-rit. #232. So, he already got level3 in it.

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
please feel free, I assigned you the same level.
