### ISSUE TITLE
[Feat]: change favicon of this website , change that to other icon , other than angular icon.

### ISSUE THREAD

**Issue by Jashwanth-rit** [sakeel-103/DFS-BFS-Graph-Travers#237]
Changing favicon to 
![favicon](https://github.com/user-attachments/assets/a19324f6-480b-4c1a-93d2-25ec487e4327)

@sakeel-103  add dssoc and hacktoberfest tag and let us to contribute

**Comment by sakeel-103** [comment]
@Jashwanth-rit 
Sorry about this, this favicon change already has been solved. 
n thank you for your contribution on this project, please find another issue or feature.
