### ISSUE TITLE
REVAMP Crowded navbar and profile dropdown on Application

### ISSUE THREAD

**Issue by shubhagarwal1** [sakeel-103/DFS-BFS-Graph-Travers#239]
![Screenshot 2024-10-16 at 3 18 28 AM](https://github.com/user-attachments/assets/62159c69-6ff4-4b61-9832-25a0922ed605)
![Screenshot 2024-10-16 at 3 18 50 AM](https://github.com/user-attachments/assets/2638ce39-15d2-4b9d-a9ce-6e0c94c5cf08)

**Comment by sakeel-103** [comment]
@shubhagarwal1 
Would you please elaborate what type of implementation you want do here .

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 Would you please elaborate what type of implementation you want do here .

hey @sakeel-103 we can transform it by making groups, like putting the simmillar thing in one and when hover ovr tha show the pages related ot htat 
like for dfs bfs a one like shoud be thee on hove it should show the pages for dfs and bfs

**Comment by shubhagarwal1** [comment]
hey @sakeel-103 can i start working on the issue

**Comment by shubhagarwal1** [comment]
hey @sakeel-103 can you please assign me this task
