### ISSUE TITLE
Integration with Firebase for User Data

### ISSUE THREAD

**Issue by shubhagarwal1** [sakeel-103/DFS-BFS-Graph-Travers#240]
Title: Migrate User Data Storage to Firebase
Details: Instead of using LocalStorage, integrate Firebase to handle user authentication and store user data (like saved graphs) in the cloud. This would allow users to log in from any device and access their saved graphs.
Benefits: Increases scalability, security, and accessibility for users.

**Comment by mehul-m-prajapati** [comment]
@sakeel-103 : There is already an issue for Auth https://github.com/sakeel-103/DFS-BFS-Graph-Travers/issues/138

**Comment by shubhagarwal1** [comment]
Hey @sakeel-10 shuoud i make a facility for users to login via firebase.

**Comment by shubhagarwal1** [comment]
> Hey @sakeel-10 shuoud i make a facility for users to login via firebase.
@sakeel-103 should i porceed with the task or should i cloase the issue

**Comment by sakeel-103** [comment]
@shubhagarwal1 
Sorry for this confusion, this issue has already been assigned to another person.

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
Please finish the backend work as soon as possible. It's already been a week.

**Comment by mehul-m-prajapati** [comment]
@sakeel-103 : okay I will push it today.
