### ISSUE TITLE
Code Editor Integration with Embedded Services

### ISSUE THREAD

**Issue by shubhagarwal1** [sakeel-103/DFS-BFS-Graph-Travers#242]
Title: Integrate an Embedded Code Editor for Practice
Details: You can embed a code editor within the DFS-BFS Graph Traversal app, allowing users to write and practice algorithms like DFS, BFS, or other graph-related problems. Services like CodeMirror, Monaco Editor (used by VS Code), or Ace Editor can be embedded into your web app.
Benefits: Gives users hands-on practice directly within the app and allows them to write, edit, and test code for solving graph problems.

Example Flow for Using the Code Editor:
User writes code: The user writes the DFS or BFS traversal code in the embedded code editor.
API Call: Upon clicking "Run", the code is sent to a service (e.g., Judge0) for execution.
Results Display: The API returns the output or errors, which are displayed on the app interface.
Test Cases: Optionally, the user’s code is tested against predefined graph inputs to validate the solution.

**Comment by sakeel-103** [comment]
@shubhagarwal1 
This this would be in the same page of the traversal or will have in different page.
