### ISSUE TITLE
[Enhancement]: enhancing the mainindex page 

### ISSUE THREAD

**Issue by Jashwanth-rit** [sakeel-103/DFS-BFS-Graph-Travers#254]
Description:
enhancement of mainindex page , with good allignment of the boxes , by using css and javascript , 

![Screenshot 2024-10-16 170603](https://github.com/user-attachments/assets/c679329f-72b7-4e90-a931-67ca2c0ceac5)

@sakeel-103 assign me this and let us to work on this issue. add hacktoberfest and gssoc tag .

**Comment by sakeel-103** [comment]
Levelassigned in first PR
