### ISSUE TITLE
[Feat]: updating navbar , options on navbar

### ISSUE THREAD

**Issue by Jashwanth-rit** [sakeel-103/DFS-BFS-Graph-Travers#257]
Description :
instead of having dropdown in navbar , having option on navbar is better thing 
Because it is much more user freindly and and user come to know these are the option available for me , once he/she enters to home page

![Screenshot 2024-10-15 230124](https://github.com/user-attachments/assets/17aa4a1c-9890-4e73-842e-aeecf7c2757f)

@sakeel-103 add Hacktoberfest tag and gssoc and assign so that i work on this.

**Comment by sakeel-103** [comment]
@Jashwanth-rit 
ok, can you provide an example of this.
Ok work on it

**Comment by Jashwanth-rit** [comment]
Yes cool , 
Example:
![Screenshot 2024-10-16 184818](https://github.com/user-attachments/assets/6333c014-adbe-46d2-838c-a7ce3603b45f)
