### ISSUE TITLE
Proposal for "Greetings" GitHub Workflow

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#26]
Hi,
I would like to propose the creation of a GitHub workflow called "Greetings."

This workflow will automatically send a warm welcome to users who create new issues or pull requests in our repository. The greeting message will be as follows:

"Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. Our team aims to respond to or assign your issue as soon as possible."

Implementing this workflow will enhance our community engagement and ensure that contributors feel valued right from the start.

**Comment by AKSHITHA-CHILUKA** [comment]
please add level labels @sakeel-103
