### ISSUE TITLE
[BUG] :  WebSocket Connection Failed, Disabling Real-Time Collaboration

### ISSUE THREAD

**Issue by rudrapratap63** [sakeel-103/DFS-BFS-Graph-Travers#261]
The WebSocket connection to the server is failing, which prevents users from accessing real-time collaboration features. This issue disrupts the core functionality of the project, as users are unable to receive or send updates in real time.

**Expected Behavior:**
The WebSocket should successfully connect, enabling real-time collaboration features 

**Actual Behavior:**
The WebSocket connection fails, and the error message is displayed in the console. As a result, all real-time collaboration features are unavailable.

![image](https://github.com/user-attachments/assets/51c19f92-4b42-42b5-955b-1f523c880f10)

**Comment by sakeel-103** [comment]
@rudrapratap63 
Sorry for this, Backend work is on process. its already been assigned.
please check #138
