### ISSUE TITLE
[Feat] : Discussion Forum Post Thread Not Working - Request to Add Separate API Endpoint and DB Schema

### ISSUE THREAD

**Issue by rudrapratap63** [sakeel-103/DFS-BFS-Graph-Travers#262]
**Description:**
The discussion forum's post thread feature is currently not functioning. When users attempt to create or view threads, the application fails to process their requests. As a result, users cannot initiate or participate in discussions, significantly impacting the engagement on the platform.

**Impact:**
- Users are unable to create new discussion threads or view existing ones.
- The engagement in discussions is severely affected due to this issue.
- The platform's main communication feature is compromised.

**Proposed Solution:**
I would like to implement a separate API endpoint specifically for handling discussion forum threads. This new endpoint will:
- Allow users to create threads with a **title** and **content**.
- Store the thread data in a **MongoDB** database for persistence.
- Support retrieval of threads for easy access and display in the forum.

https://github.com/user-attachments/assets/62bc15cf-6fac-4489-b5a9-47f4cf82d496

**Comment by rudrapratap63** [comment]
@sakeel-103, if it's okay with you, could you please label this issue as level 3? I would love the opportunity to work on adding the database schema and creating the functional backend for it. Thank you!

**Comment by sakeel-103** [comment]
"@rudrapratap63 
thank you for raising this issue. Let me inform you that the backend work is in progress and has already been assigned 
#138 
Please wait until the other person finishes the backend work, after which I'll assign this issue to you for backend implementation."

**Comment by rudrapratap63** [comment]
@sakeel-103 ok sir
