### ISSUE TITLE
[Bug]: start-exploring Button not working , 

### ISSUE THREAD

**Issue by Jashwanth-rit** [sakeel-103/DFS-BFS-Graph-Travers#275]
Description:
In Home page onClick of startexploring , that should travel us to login or sign up page , after verification it should travel us to mainindex page 
flow broken 

![Screenshot 2024-10-17 155742](https://github.com/user-attachments/assets/36332726-d5ca-4ab3-936b-db8a5198b62a)

**Comment by sakeel-103** [comment]
@Jashwanth-rit 
Approach is 👎 
LandingPage -> Signup/Login -> MainIndex Page -> Traversal Page. 
Please make sure of this.

**Comment by Jashwanth-rit** [comment]
@sakeel-103 yes sure,
