### ISSUE TITLE
No "logout"" option after login

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#29]
- There is no button to logout

**Comment by sakeel-103** [comment]
If you're adding a logout function, please review the code thoroughly. I've intentionally left some errors in the signup and login functions for contributors to address.
as well as in the backend, I stored the data in local storage instead of using MongoDB or other databases.

**Comment by sakeel-103** [comment]
this has been assigned to you, please work on it.
