### ISSUE TITLE
Error: Page not found on clicking start exploring

### ISSUE THREAD

**Issue by mansiruhil13** [sakeel-103/DFS-BFS-Graph-Travers#292]
![Screenshot 2024-10-18 015756](https://github.com/user-attachments/assets/423fb150-9377-451d-b011-9a3029b08682)
![Screenshot 2024-10-18 015746](https://github.com/user-attachments/assets/44c6ae90-b438-4751-829b-7b8c0fa91713)

**Comment by mehul-m-prajapati** [comment]
@sakeel-103 : I addressed this issue here: https://github.com/sakeel-103/DFS-BFS-Graph-Travers/issues/265

This missing part is how website is built for prod. 
This modified netlify.toml should fix this.
```
[build]
  publish = "dist/eccom-prj/browser" 
  command = "ng build --prod"  # Ensure you're building for production
  
[[redirects]]
  from = "/*"
  to = "/header.component.html"
  status = 200
```

**Comment by sakeel-103** [comment]
@mansiruhil13 
its already assigned, please work on another feature.
