### ISSUE TITLE
Add: A description of algorithm

### ISSUE THREAD

**Issue by LifeHashed** [sakeel-103/DFS-BFS-Graph-Travers#3]
A brief description of the Algorithm BFS and DFS so that people can under stand what the algorithm does. I propose creating button next to the simulator to show what the algorithm is performing 

Maintainers please assign me this issue and add the gssoc-ext label

**Comment by LifeHashed** [comment]
I have added a PR to resolve the issue. Please accept it if it is admissible

**Comment by sakeel-103** [comment]
Done !!!
