### ISSUE TITLE
Invalid response format after signup

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#30]
- Application is expecting a JSON response from the server, but it’s receiving a plain text response instead.

**Comment by sakeel-103** [comment]
will you please elaborate with some examples ?

**Comment by mehul-m-prajapati** [comment]
![Capture](https://github.com/user-attachments/assets/6f1ec6cc-fc01-4822-921e-f683f3e2219a)
![Capture1](https://github.com/user-attachments/assets/7361fab5-bc2c-4463-a87a-f54e1814b18f)

**Comment by sakeel-103** [comment]
Done !

**Comment by AKSHITHA-CHILUKA** [comment]
please add level labels @sakeel-103
