### ISSUE TITLE
[Bug]: wrong theme for Github-Contributors page and faq page .

### ISSUE THREAD

**Issue by Jashwanth-rit** [sakeel-103/DFS-BFS-Graph-Travers#303]
Description:
all the other page has white as page color , but Faq and github contributor page has Black as Background, if we have uniformity , looks good and premium.

https://github.com/user-attachments/assets/1834f69b-d91b-4542-affa-31d3167ceb08

@sakeel-103 add gssoc and hacktoberfest tag and assign this to me.

**Comment by sakeel-103** [comment]
@Jashwanth-rit 
Ok, but change theme accordingly as well as the color

**Comment by Jashwanth-rit** [comment]
yeah, sure.
