### ISSUE TITLE
[Enhance]: Adding logo to mainindex page as well.

### ISSUE THREAD

**Issue by Jashwanth-rit** [sakeel-103/DFS-BFS-Graph-Travers#308]
Description: 
Adding logo to mainindex page as well, which makes it look premium 

Image:
![Screenshot 2024-10-18 140950](https://github.com/user-attachments/assets/d85ff399-906a-4058-92da-f342988606b5)

@sakeel-103 add Gssoc and hacktober fest tag and assign me.

**Comment by sakeel-103** [comment]
@Jashwanth-rit 
logo already added in the landing page also the navbar items going out of the navbar. Fix these issues as well implement the logo in each and every page.
