### ISSUE TITLE
[Feat]: Once after User signed in , he should be navigate to home page.

### ISSUE THREAD

**Issue by Jashwanth-rit** [sakeel-103/DFS-BFS-Graph-Travers#321]
Description : 
 once user signed in he should go to home page not to login page.

Because:
 we are Building User-centered website time of user matters for us , once user signed in , it not required verify him by loging him in , Because he have just logged in .

https://github.com/user-attachments/assets/5cf7bcbb-38c4-44bc-9ed8-ff99d205c76a

@sakeel-103 add gssoc and hacktoberfest tag

**Comment by mehul-m-prajapati** [comment]
@Jashwanth-rit : issue already there https://github.com/sakeel-103/DFS-BFS-Graph-Travers/issues/138

@sakeel-103 : Time to report this guy @Jashwanth-rit to Program Manager and Black list him

**Comment by Jashwanth-rit** [comment]
you will  solve this Issue next year , where is this issue , we are in #322  issue , your are having #138 , solve issue , just creating issue and leaving is not a Gssoc , contribution  is possible only when you solve the problem . 

i think You understood.

**Comment by Jashwanth-rit** [comment]
@mehul-m-prajapati Behave good , have kindness , Gssoc wont remain with you till end , humanity remains till end.
have that bit.

**Comment by mehul-m-prajapati** [comment]
@Jashwanth-rit : Bro, this is 3rd time, I am seeing you copy someone else's issues. 
You don't know the meaning of patience. Please refer to dictionary and after understanding patience, talk about humanity

**Comment by Jashwanth-rit** [comment]
@mehul-m-prajapati there nothing shout on me , u created long back , which is invisible, if need to create issue by watching all the past issues, then we should contribute after gssoc get over.

**Comment by Jashwanth-rit** [comment]
@mehul-m-prajapati just say don't shout , I understand and I will close my issue .

**Comment by Jashwanth-rit** [comment]
@mehul-m-prajapati I am not coping anyone issues , read my issue properly my issue is completely different than yours .

**Comment by sakeel-103** [comment]
@Jashwanth-rit 
Backend user authentication work is done now.
Ok, your approach is fine, suppose a user signup after that they landed to the home page. Now he wants to logout and then login by the registered credential then they should be able to login.
please make sure that your approach will work like this.
