### ISSUE TITLE
[Bug]: Login page not verifies whether the User is signed in or not .

### ISSUE THREAD

**Issue by Jashwanth-rit** [sakeel-103/DFS-BFS-Graph-Travers#322]
Description :
when user try to login , there should be verification for whether user have account or not , 

some random email and password , login accepts , so login page should verify whether user as signed in or not .

https://github.com/user-attachments/assets/2ca94c47-9656-44cf-9e1b-0bb5d7dfc310

**Comment by mehul-m-prajapati** [comment]
@Jashwanth-rit : issue already there #138

@sakeel-103 : Time to report this guy @Jashwanth-rit to Program Manager

**Comment by Jashwanth-rit** [comment]
@mehul-m-prajapati I am not coping anyone issues , read my issue properly my issue is completely different than yours .

**Comment by sakeel-103** [comment]
@Jashwanth-rit 
Duplicate issue, you have already raised this.

**Comment by Jashwanth-rit** [comment]
@sakeel-103 No this is not duplicate issue , 
Reason, in the issue #304 I just added requirement or validation that user should enter , but in this issue I am pointing on checking whether the user exists or not .

**Comment by mehul-m-prajapati** [comment]
@Jashwanth-rit : Middleware issue is already there #135 , I will open PR for that today.

**Comment by Jashwanth-rit** [comment]
First user should full fill the validation and then backend checks whether the user exists ,
 
We had other approach as well 
Approach1 : entering some random and checking whether user exists 
Or 
Approach2 : entering valid or required data and then checking for user exists .

I think second one makes more sense.

**Comment by Jashwanth-rit** [comment]
Ok then, u can resolve and close me issue as well 
Fine .

**Comment by sakeel-103** [comment]
> @sakeel-103 No this is not duplicate issue , Reason, in the issue #304 I just added requirement or validation that user should enter , but in this issue I am pointing on checking whether the user exists or not .

Ok fine, later on I will see first work on the previous issue.
