### ISSUE TITLE
Adding more Visualizations to Interactive Graph Visualizer

### ISSUE THREAD

**Issue by Riyachauhan11** [sakeel-103/DFS-BFS-Graph-Travers#326]
I would like to add DFS and Dijkstra's algo visualizer in the Interactive Graph Visualizer section of home page. As the part above this section is talking about DFS, BFS and Dijkstra's algo it would be good to add visualizers for all.

![image](https://github.com/user-attachments/assets/8ea90156-0aaf-4d1d-bbb1-09c122f1b364)

![image](https://github.com/user-attachments/assets/8ecd5da5-2247-4c29-b4b0-b0b2788ed174)

**Comment by sakeel-103** [comment]
@Riyachauhan11 
DFS/ BFS graph visualization is already there. First check the visualization then work on this issue.

**Comment by Riyachauhan11** [comment]
> @Riyachauhan11 DFS/ BFS graph visualization is already there. First check the visualization then work on this issue.

@sakeel-103 pretty sure there's only BFS visualization available on displayed website. Kindly lemme know if im wrong as im only able to see that one.
![image](https://github.com/user-attachments/assets/a294f175-948e-47fb-b385-310fb4d72557)

https://github.com/user-attachments/assets/ba115ba3-a54f-41cd-afe4-d9488890af65
