### ISSUE TITLE
Add Login/SignUp with Google using OAuth in frontend

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#331]
Implement Google OAuth authentication to allow users to log in or sign up using their Google accounts. This feature should include a "Login with Google" button on the login and signup pages. Upon successful authentication, users should be redirected to their dashboard or the appropriate landing page.

**Comment by meghanakn473** [comment]
@sakeel-103 please assign me this issue i want to work on it, i have previous experience on working with it

**Comment by mehul-m-prajapati** [comment]
@meghanakn473 : Read this https://github.com/GSSoC24/Contributor/tree/main/gssoc-guidelines#meaningful-contribution-guidelines

![g1](https://github.com/user-attachments/assets/5e8e66aa-0cd0-4b57-906a-d223c42de3c1)

**Comment by mehul-m-prajapati** [comment]
@meghanakn473 : You need to raise your own issues.

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
google authentication login is already there. please cross verify then work

**Comment by mehul-m-prajapati** [comment]
@sakeel-103 : It always returns success message. There is no backend Google API integration.
![c1](https://github.com/user-attachments/assets/82dae320-6a97-45f5-81e4-4b1e2363544c)

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
Ok bro, go ahead
