### ISSUE TITLE
Refactor backend code to use middleware functions

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#36]

**Comment by sakeel-103** [comment]
Before working on the signup/login form, remember that the signup form data is being stored in local storage. I haven't connected it to MongoDB or any other databases.

**Comment by mehul-m-prajapati** [comment]
- Yes, I know that. I will add MongoDB cloud database for backend operations.

**Comment by sakeel-103** [comment]
thank you, I'll review it and then merge it.

**Comment by sakeel-103** [comment]
Completed !!

**Comment by AKSHITHA-CHILUKA** [comment]
please add level labels @sakeel-103
