### ISSUE TITLE
Add Quiz challenges and show result

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [sakeel-103/DFS-BFS-Graph-Travers#376]
Add Quiz challenges and show result

**Comment by sakeel-103** [comment]
@KapuluruBhuvaneswariVspdbct 
this feature has already added, check first then work.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
<img width="654" alt="image" src="https://github.com/user-attachments/assets/31cceed0-3960-4615-a656-51fe60ac7968">
showing the errors inbuilt
