### ISSUE TITLE
Implement Session Management to Remember Logged-In User Across Reloads

### ISSUE THREAD

**Issue by Dipu2552003** [sakeel-103/DFS-BFS-Graph-Travers#38]
Currently, users need to re-enter their login credentials every time the page reloads or they revisit the site, which disrupts the user experience. I propose implementing session management to remember the logged-in user across page reloads, eliminating the need to go through the login page repeatedly.

By storing session data securely on the backend, the system can verify the user’s session on each page load. This improvement will streamline the user journey and improve overall usability, ensuring that logged-in users can seamlessly access the site without unnecessary interruptions. The backend modification will involve handling session tokens or user identifiers to persist the login state effectively.
![design](https://github.com/user-attachments/assets/84df6637-8d85-4149-bfd4-4cd20cb48de4)

@sakeel-103

**Comment by sakeel-103** [comment]
before working on the signup/login form, remember that the signup form data is being stored in local storage. I haven't connected it to MongoDB or any other databases.

**Comment by Dipu2552003** [comment]
> before working on the signup/login form, remember that the signup form data is being stored in local storage. I haven't connected it to MongoDB or any other databases.

Yes, I have kept that in mind while working on the signup/login form. I have improved the logic of the login page to ensure proper functionality. If there are any further issues or questions, please let me know, and I will be happy to explain the code in the pull request.
