### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [sakeel-103/DFS-BFS-Graph-Travers#384]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @sakeel-103 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by smog-root** [comment]
Add level3 label!!!

**Comment by sakeel-103** [comment]
@smog-root 
Work on it while merging I will assign levels

**Comment by sakeel-103** [comment]
and please attach demo video of that, if possible
