### ISSUE TITLE
Enhancement: UI Improvement for Footer

### ISSUE THREAD

**Issue by ruhilmansi** [sakeel-103/DFS-BFS-Graph-Travers#398]
![Screenshot 2024-10-22 100937](https://github.com/user-attachments/assets/6694b2c7-6bc6-44ed-9a27-9c55b3998ef4)

**Comment by mansiruhil13** [comment]
there is overlapping, I can change UI, so that it looks better.

**Comment by mansiruhil13** [comment]
can you assign me? @sakeel-103

**Comment by sakeel-103** [comment]
@mansiruhil13 
Apologize, this issue has already been assigned.
#393
