### ISSUE TITLE
Bug: BFS and DFS in navbar does not work

### ISSUE THREAD

**Issue by LifeHashed** [sakeel-103/DFS-BFS-Graph-Travers#4]
![image](https://github.com/user-attachments/assets/274235c4-9b5d-43bc-8a78-29ef0afb477c)
 These links does not work

Maintainers please assign me this issue and give the gssoc-ext label

**Comment by sakeel-103** [comment]
I haven't worked on these navbar tags as buttons, but if you'd like to work on them, feel free to work.

**Comment by LifeHashed** [comment]
Sure thank you so much

**Comment by LifeHashed** [comment]
Please reveiw the PR and merge if it is admissable

**Comment by LifeHashed** [comment]
Can you also add hacktoberfest-accepted

**Comment by sakeel-103** [comment]
@LifeHashed 
Just to let you know, I am both the project admin and the maintainer of this project.

**Comment by sakeel-103** [comment]
Done.

**Comment by LifeHashed** [comment]
That is very good to know. I am sorry if I misinterpreted you in any way
