### ISSUE TITLE
Add forgot password option in the login page

### ISSUE THREAD

**Issue by Debasmita1701** [sakeel-103/DFS-BFS-Graph-Travers#41]
For any login/signup page for a user its convenient to have forgot password option as it help then to retrieve the password in case they forgot their password 
I think this feature should be added in the login 
I would  request  @sakeel-103  to assign this issue to me 
<img width="1127" alt="Screenshot 2024-10-05 at 8 18 09 PM" src="https://github.com/user-attachments/assets/b661bd0c-c408-4343-8534-918f29ae8370">

**Comment by sakeel-103** [comment]
Sure, please work on this.

**Comment by rudrapratap63** [comment]
Hello @Debasmita1701, if you are facing any issues related to the 'Forgot Password' feature, feel free to let me know, and I will help.

**Comment by Sourabh782** [comment]
Hii, can i contribute to this issue? @sakeel-103
