### ISSUE TITLE
[BUG] : The current chatbot is not working properly !!!

### ISSUE THREAD

**Issue by SrijaVuppala295** [sakeel-103/DFS-BFS-Graph-Travers#419]
![image](https://github.com/user-attachments/assets/9091bb13-4022-4623-a3e1-6aa227080722)

@sakeel-103 , please assign me under this issue !!! I will create a new chatbot and currently the chatbot color is black , i will set it according to the theme and make sure that it will answer all the questions related to algo !!!

**Comment by SAMluci666** [comment]
Has there been any update? I am open to work or collaborate on this issue. 
@sakeel-103 @Harikrishnan6336

**Comment by SrijaVuppala295** [comment]
@sakeel-103 @SAMluci666 , bro i will merge it by today !!!
