### ISSUE TITLE
Footer is not designed..

### ISSUE THREAD

**Issue by Meetpidev** [sakeel-103/DFS-BFS-Graph-Travers#437]
### As you can see that the footer is so much crowded.. need proper design with responsiveness.. 

![image](https://github.com/user-attachments/assets/7ecccdfb-79d1-42de-b953-6e1b260ed8e5)

**Comment by sakeel-103** [comment]
@Meetpidev 
Make sure that the function should remain as it has

**Comment by Meetpidev** [comment]
@sakeel-103 Please Review PR again.. i updated it..

**Comment by Meetpidev** [comment]
@sakeel-103 Please review PR...
