### ISSUE TITLE
FEATURE:Add visulizing of all the sorting algorithm..

### ISSUE THREAD

**Issue by Meetpidev** [sakeel-103/DFS-BFS-Graph-Travers#447]
### Feature Summary

Add visulizing of all the sorting algorithm..

### Description

Add visulizing of all the sorting algorithm..

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by sakeel-103** [comment]
@Meetpidev 
Please give a star of this repository

**Comment by sakeel-103** [comment]
@Meetpidev 
bro the logo is an image so work accordingly

**Comment by Meetpidev** [comment]
@sakeel-103  Please review PR..

**Comment by Meetpidev** [comment]
@sakeel-103 review PR..
