### ISSUE TITLE
Add graceful shutdown of backend server 

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#46]
Implement a graceful shutdown for your server. This is useful for cleaning up resources when the server stops.

**Comment by AKSHITHA-CHILUKA** [comment]
please add level labels @sakeel-103

**Comment by sakeel-103** [comment]
@AKSHITHA-CHILUKA 
Thanks !

**Comment by AKSHITHA-CHILUKA** [comment]
please add level labels to all your issues and pr which are open and closed

**Comment by sakeel-103** [comment]
@AKSHITHA-CHILUKA 
Is it necessary to add levels to the open issues rii8 now, or can I add them when I merge and close them.

**Comment by AKSHITHA-CHILUKA** [comment]
now you have to add

**Comment by AKSHITHA-CHILUKA** [comment]
add level labels to all issues and  pr's

**Comment by sakeel-103** [comment]
@AKSHITHA-CHILUKA 
could u plz provide the guidelines for all the levels, like level1 is for what type of works and 2 and 3.

**Comment by AKSHITHA-CHILUKA** [comment]
it depends on the issue you have to decide the difficulty of the issue raised and then you have to assign the levels
