### ISSUE TITLE
FEATURE:add chatbot integration to website

### ISSUE THREAD

**Issue by Ankul8471** [sakeel-103/DFS-BFS-Graph-Travers#471]
### Feature Summary

add chatbot integration to website

### Description

add chatbot integration to website

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by Ankul8471** [comment]
@sakeel-103  assign me

**Comment by Ankul8471** [comment]
@sakeel-103  please assign me it help me a lot

**Comment by sakeel-103** [comment]
@Ankul8471 
Chatbot feature has already done 
. But you can make it more user friendly.
