### ISSUE TITLE
Improve Footer Design for Better Aesthetics.

### ISSUE THREAD

**Issue by shaina123786** [sakeel-103/DFS-BFS-Graph-Travers#479]
### Feature Summary

Revamp the footer design to enhance readability and organization, creating a cleaner and more visually appealing layout.

### Description

The current footer design appears cluttered, making it difficult for users to find information quickly. Improving the design will enhance user experience, add aesthetic value, and ensure a more organized structure for key information and navigation links.

### Proposed Solution

Redesign the footer with a more streamlined layout, ensuring consistency in font size, colors, and spacing. Group related elements logically, use icons where appropriate, and incorporate a responsive layout for various devices. User story: As a user, I want to easily navigate the footer to find links and information without visual clutter.

### Screenshots/Logs

![image](https://github.com/user-attachments/assets/8666c372-8703-45e8-8445-03de379e2e19)

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by sakeel-103** [comment]
@shaina123786 
In the footer "newsletter" section displaying two times. Please take care of this and correct the alignments and correct the display flexbox of the footer.

**Comment by shaina123786** [comment]
Okk
