### ISSUE TITLE
FEATURE: Redesigning of Footer

### ISSUE THREAD

**Issue by Shariq2003** [sakeel-103/DFS-BFS-Graph-Travers#497]
### Feature Summary

I want to Completely redesign the Footer

### Description

Current Footer is totally messed up, and distort the UI and UX.

![image](https://github.com/user-attachments/assets/3dd99ded-cde2-4f75-ad94-f7e727f034e8)

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by sakeel-103** [comment]
@Shariq2003 
redesigning the footer has already been assigned.
Please check #476

**Comment by Shariq2003** [comment]
@sakeel-103 sir, the footer code is broken completely,
I will fix this by tonight, please assign to me.

**Comment by Shariq2003** [comment]
@sakeel-103 sir, thanks for assigning, will raise PR by today.
