### ISSUE TITLE
Improving the Alignment of exploring various graphs !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [sakeel-103/DFS-BFS-Graph-Travers#511]
![image](https://github.com/user-attachments/assets/d2293a49-d816-455f-8f9b-7b34b27bfe94)

**Comment by SrijaVuppala295** [comment]
@sakeel-103 , please assign me under this issue !!

**Comment by sakeel-103** [comment]
@SrijaVuppala295 
please do not submit a PR without being assigned. Next time, I will not merge it
