### ISSUE TITLE
FEATURE: Improving the Quiz page !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [sakeel-103/DFS-BFS-Graph-Travers#516]
### Feature Summary

I want to improve the questions and answers in the quiz page !!

### Description

It improves the user experience !!

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by vish4lsharma** [comment]
I'm eager to contribute to the "Improving the Quiz page" feature (#516) and I see that three tasks have already been completed. Could you share how I can assist further?
