### ISSUE TITLE
BUG: Add proper signup page

### ISSUE THREAD

**Issue by NK-Works** [sakeel-103/DFS-BFS-Graph-Travers#525]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

The signup page doesnt load properly and shows error

### Steps to Reproduce

go to home
click get started
see error

### Expected Behavior

when get started clicked signup page should be shown

### Screenshots/Logs

![image](https://github.com/user-attachments/assets/5d4d7dee-6100-4e25-885a-43c818e04523)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by mehul-m-prajapati** [comment]
@NK-Works : sign up page is there, it is a deployment issue on vercel.
Try running this on local host, you will see sign up page.

You need to solve deployment problem for this one

**Comment by sakeel-103** [comment]
> @NK-Works : sign up page is there, it is a deployment issue on vercel. Try running this on local host, you will see sign up page.
> 
> You need to solve deployment problem for this one

@NK-Works 
yes, that's correct.. I apologize for this, bcz my project deployment time waslimited to just one month, and that period has now ended. Plz run the project on local host

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
thank you !

**Comment by sakeel-103** [comment]
@NK-Works 
please close the issue
