### ISSUE TITLE
ADD some chaotic webelements page that portrays the dfs and bfs algo journey 

### ISSUE THREAD

**Issue by shubhagarwal1** [sakeel-103/DFS-BFS-Graph-Travers#542]

**Comment by sakeel-103** [comment]
@shubhagarwal1 
ok, could you please elaborate

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 ok, could you please elaborate

Hey @sakeel-103, i will be adding Visual Stack and Queue Displays:

visual representation of the stack (for DFS) and queue (for BFS) that updates dynamically as the algorithms run.
Show the current contents of the stack and queue with animated additions and removals.

**Comment by sakeel-103** [comment]
@shubhagarwal1 
ok, fine
