### ISSUE TITLE
Adding 5 Games that can help students to learn dfs and bfs more interestingly 

### ISSUE THREAD

**Issue by shubhagarwal1** [sakeel-103/DFS-BFS-Graph-Travers#545]
**This issue i will be completin in 4 PR picking two games each PR all these games will be on one page but user can switch the tabs to change the games**
**###########Done###############** 
Maze Runner
Implementation: Create a grid-based maze. Use DFS to explore paths recursively until the exit is found, marking visited paths. BFS can be used to find the shortest path by exploring all neighbors level by level.

Treasure Hunt
Implementation: Set up a grid or graph where treasures are scattered. DFS can be used to explore deeper paths for treasures, while BFS finds the closest treasure by exploring neighboring cells first.

**###########Pending###############** 
Pathfinder
Implementation: Allow users to set start and end points on a grid. Implement BFS to find the shortest path in terms of steps, and DFS for exploring all possible routes to reach the destination.

Escape the Dungeon
Implementation: Design a dungeon with multiple rooms connected by passages. Use DFS to explore every room deeply, simulating a character’s attempt to escape, while BFS can be used to calculate the quickest escape route.

Forest Explorer
Implementation: Create a forest grid where nodes represent trees. Use DFS to explore deep into the forest for specific objectives (like finding a rare plant), while BFS is used to find paths to nearby objectives or exits.

Island Hopper
Implementation: Represent islands as nodes in a graph and connections as edges. BFS can be used to explore all reachable islands efficiently, while DFS explores deep into specific routes or paths to find hidden treasures.

Grid Escape
Implementation: Design a grid with barriers and open paths. Implement BFS to find the shortest escape route from a starting point to an exit while using DFS for exploring various escape routes through the grid.

Robot Navigator
Implementation: Create a grid where a robot must navigate to a target. Use BFS for optimal pathfinding to avoid obstacles, and DFS for testing alternative routes in case of blockages.

Treasure Maze
Implementation: Set up a maze where treasures are randomly placed. Use DFS to explore deep pathways to find treasures, and BFS to find the shortest route to the closest treasure.

Tower Traverser
Implementation: Build a tower with multiple floors and rooms. Use DFS to explore each room on a floor deeply before moving to the next floor, while BFS can help find the fastest route to a specific room or floor.

**Comment by shubhagarwal1** [comment]
Hey @sakeel-103 This issue i will be completin in 4 PR picking two games each PR all these games will be on one page but user can switch the tabs to change the games

**Comment by sakeel-103** [comment]
@shubhagarwal1 
Just a reminder msg, 
To complete your implementation, as soon as you can.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 Just a reminder msg, To complete your implementation, as soon as you can.

yes @sakeel-103 i will be raising the PR,s today itself, thankyou for the ack.
