### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by jainaryan04** [sakeel-103/DFS-BFS-Graph-Travers#549]
Description of the Feature
Implementing dark mode improves user comfort by reducing eye strain and glare, especially in low-light environments. It enhances readability, conserves battery on OLED devices, and aligns with modern design practices. Supporting dark mode will offer a better user experience and accessibility, catering to diverse user preferences.

Proposed Solution
Dark mode can be implemented using a custom React hook to manage theme state. The hook toggles between light and dark themes, updating the class on the root element. CSS classes (e.g., .dark or .light) control styling. The hook listens to system preferences and persists the theme in localStorage.

**Comment by jainaryan04** [comment]
currently some parts have a dark background and some have a white bg. should i change it all to white for light mode and all to black for dark ? @sakeel-103

**Comment by sakeel-103** [comment]
@jainaryan04 
sure, dark mode means what, when we click for light mode then all the pages should be light and for dark then all should be dark.
