### ISSUE TITLE
Feature: Add backend route to store user details in db when Signin using Google

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#550]

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
Ok, add one feature like that when a user logs in, their account remains active and is displayed in the navbar until they log out. Also, track all activities they perform after logging in. 
-remove the login form from the 'Start Exploring' button on the landing page and add it to the navbar. When the user clicks there, the form should be displayed.
- and please work according to your approach.

demo- 
![nnn](https://github.com/user-attachments/assets/b587847d-cc43-4be4-b942-ee59eb36f182)

**Comment by mehul-m-prajapati** [comment]
@sakeel-103 : okay, thanks for valuable suggestions.

- I will implement those changes in this PR

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
Here is one more feature required in this project. If you want to work, then go ahead
- Create a new task to work on the feedback form. Display an icon on the left side of the screen, similar to a chatbot. When the icon is clicked, the feedback form should open.

**Comment by mehul-m-prajapati** [comment]
Okay, added the new issue #551

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
this is a remainder message that 10th is the last date for the end of gssoc'24_Extd. So please work on this issue as soon as you can.
