### ISSUE TITLE
Add 'About Us' Page and Fix Navbar Height

### ISSUE THREAD

**Issue by rudrapratap63** [sakeel-103/DFS-BFS-Graph-Travers#58]
I would like to propose adding an "About Us" page to the project. The page can include information about the project's goals, contributors, and any other relevant details. This will help new users and contributors understand the purpose and background of the project.

Additionally, I noticed that the current navigation bar is taking up more height than necessary, which is affecting the overall design and user experience. I suggest adjusting the CSS properties to reduce the height and improve the appearance.

Proposed Solution:

1. Create an 'About Us' Page:
- Include a brief introduction to the project.
- Add sections like "Our Mission", "Contributors", and "Contact Information".
- Link this page in the navbar for easy access.
2. Fix Navbar Height:
- Adjust the CSS properties to reduce the height of the navbar.
- Ensure that the navbar remains responsive and visually appealing across different screen sizes.

 I would like to work on this issue @sakeel-103 so please assign me. Let me know if there are any specific details you would like to be included on the "About Us" page.

**Comment by sakeel-103** [comment]
that's a good idea. Please go ahead and work on it.

**Comment by rudrapratap63** [comment]
@sakeel-103 Thank you! I'll start working on it right away. I'll make sure to reference the issue number in my PR to keep everything organized.

**Comment by rudrapratap63** [comment]
Hello @sakeel-103, I fixed the navbar height and would like to know what content or elements you would like me to add to the About Us page.

**Comment by rudrapratap63** [comment]
@sakeel-103, please check the following video, and let me know if you want any other changes.

https://github.com/user-attachments/assets/1a72b9aa-0068-4dd5-918e-795b1ceb35cc
