### ISSUE TITLE
BUG: Remove duplicate Subscribe to our newsletter text box

### ISSUE THREAD

**Issue by Subhajit-2023-44** [sakeel-103/DFS-BFS-Graph-Travers#585]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

I want to Remove duplicate Subscribe to our newsletter text box

![Screenshot 2024-11-09 170332](https://github.com/user-attachments/assets/9b41a958-357d-436e-a6ed-b64f22df01cd)

### Steps to Reproduce

.

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by Subhajit-2023-44** [comment]
@sakeel-103 assign me with Level and gssoc-ext label

**Comment by sakeel-103** [comment]
@Subhajit-2023-44 
already assigned 
#569
