### ISSUE TITLE
FEATURE: Add header and Footer

### ISSUE THREAD

**Issue by Subhajit-2023-44** [sakeel-103/DFS-BFS-Graph-Travers#586]
### Feature Summary

I want to Add header and Footer

![Screenshot 2024-11-09 170555](https://github.com/user-attachments/assets/449b9b0c-da73-4ec0-b42d-db0fffe75282)
![Screenshot 2024-11-09 170602](https://github.com/user-attachments/assets/b174997e-ab83-481d-9317-c1694fb6ef66)

### Description

.

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by Subhajit-2023-44** [comment]
@sakeel-103 assign me with Level and gssoc-ext label

**Comment by mehul-m-prajapati** [comment]
Duplicate #534

**Comment by Subhajit-2023-44** [comment]
> Duplicate #534

Okay no problem
