### ISSUE TITLE
❗[BUG] : Incorrect API Endpoint in Signup Request and Sensitive Data Logged in Console

### ISSUE THREAD

**Issue by rudrapratap63** [sakeel-103/DFS-BFS-Graph-Travers#59]
I noticed an issue in the signup functionality of the project. When a user tries to sign up, the request is being sent to `http://localhost:5000/api/signup`, which is not the correct endpoint. This may cause the signup process to fail or result in a network error, especially when deployed in a production environment.

**Steps to Reproduce:**
1.Open the signup page in the project.
2.Fill in the signup form and submit it.
3.Check the console log for sensitive data and the network tab for the incorrect request being sent to http://localhost:5000/api/signup.

![Screenshot 2024-10-07 213910](https://github.com/user-attachments/assets/18b9301e-6a5f-49d6-8556-651f6eabfa81)

![Screenshot 2024-10-07 214105](https://github.com/user-attachments/assets/44cade64-ebe6-44d8-8fc8-09142d479e65)

**Comment by rudrapratap63** [comment]
@sakeel-103 , if you want me to correct all the authentication issues and also want to add a 'Forgot Password' feature, then let me know.

**Comment by rudrapratap63** [comment]
@sakeel-103 Please mention level3 or level2 label  .

**Comment by sakeel-103** [comment]
@rudrapratap63 
sure, please go ahead and work on it.

**Comment by rudrapratap63** [comment]
Hello Sir @sakeel-103,
I am adding an environments folder in the `src `directory, along with two `environment `files: one for development and another for production.
![image](https://github.com/user-attachments/assets/db464740-19c7-4c0c-9219-442dbc0e596e)

I thinking to add following code inside scripts in package.json file
"build:dev": "ng build --configuration development",
"build:prod": "ng build --configuration production",
![image](https://github.com/user-attachments/assets/057fd05f-9e74-41d7-a262-35396df6aabd)

**Comment by sakeel-103** [comment]
Done !!!
