### ISSUE TITLE
FEATURE: Add a pop up dialog box for subscribing to newsletter ✨✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [sakeel-103/DFS-BFS-Graph-Travers#591]
### Feature Summary

I want to add a pop up dialog box for subscribing to newsletter..

PA please assign me for this task..

### Description

.

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by Subhajit-2023-44** [comment]
@sakeel-103 sir please add level 3

**Comment by mehul-m-prajapati** [comment]
@Subhajit-2023-44 don't beg levels. PA will assign it according to PR code changes
