### ISSUE TITLE
FEATURE: Add Signup/Register page 🟢

### ISSUE THREAD

**Issue by Subhajit-2023-44** [sakeel-103/DFS-BFS-Graph-Travers#593]
### Feature Summary

I want to create a Signup/Register page.. please assign me..

### Description

.

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by mehul-m-prajapati** [comment]
Already there

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
thank you 

@Subhajit-2023-44  already there
