### ISSUE TITLE
FEATURE: Add Feedback/Rate Us page ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [sakeel-103/DFS-BFS-Graph-Travers#594]
### Feature Summary

I want to add a Add Feedback/Rate Us page...

PA please assign me this task.

### Description

.

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by mehul-m-prajapati** [comment]
Already there
