### ISSUE TITLE
Add validation message below the user name field

### ISSUE THREAD

**Issue by shubhagarwal1** [sakeel-103/DFS-BFS-Graph-Travers#64]
I propose to add the validation message below the user name field instead of the alert message commign which looks very much not clean

<img width="1149" alt="Screenshot 2024-10-08 at 4 38 29 PM" src="https://github.com/user-attachments/assets/4a786c52-c765-4f95-86a8-9f26debb1176">

@sakeel-103 please assign this task to me

**Comment by sakeel-103** [comment]
good idea !
