### ISSUE TITLE
Conditional Login Form Submission Based on User Input

### ISSUE THREAD

**Issue by itbindu** [sakeel-103/DFS-BFS-Graph-Travers#69]
In this login system, the login button remains disabled until the user manually enters both the username and password. This ensures that users cannot bypass the login page without providing valid credentials. This approach ensures a secure and user-driven l

https://github.com/user-attachments/assets/6af2f203-1f5c-4403-aa20-37f1bc02595cogin process, preventing any form of automatic login submission. pls assign me

**Comment by sakeel-103** [comment]
ok !
