### ISSUE TITLE
Make custom graphs and visualize how it is traversed 

### ISSUE THREAD

**Issue by LifeHashed** [sakeel-103/DFS-BFS-Graph-Travers#7]
Make custom graphs using a form and based on that a graph is drawn. Then our algo visualizes it

**Comment by sakeel-103** [comment]
I've assigned this to you. Please work on it

**Comment by LifeHashed** [comment]
I have made a few changes. The custom graph feature is implemented. Please look into it if possible for any corrigendum

**Comment by sakeel-103** [comment]
Done !!
