### ISSUE TITLE
[FEATURE ENHANCEMENT] Adding Header aand Footer to make navigation easy ✨

### ISSUE THREAD

**Issue by iamendless10** [sakeel-103/DFS-BFS-Graph-Travers#71]
Hello @sakeel-103 the header in the homepage is not looking good so i wish to work in the header part and also in the footer part, and i will also create a logo for our project. Assign me under gssoc-ext and hacktoberfest so that i can start working immediately.

![image](https://github.com/user-attachments/assets/e4d7ac67-e944-488e-a41c-7288e90cff12)

**Comment by sakeel-103** [comment]
@iamendless10 
Srry for this,
I haven't given the footer section bcz there is no for a footer section, but you want to add, then add only in the home page, if you wish
