### ISSUE TITLE
SignUp and Login Form Validation Checking should be done by the field Alerts not by Windows Alerts

### ISSUE THREAD

**Issue by Shariq2003** [sakeel-103/DFS-BFS-Graph-Travers#73]
https://github.com/user-attachments/assets/24d0e708-2ec9-4977-bdbf-1a43d49082be

I will add form validations and better Popups only for success else fileds alerts for failures.

**Comment by Shariq2003** [comment]
@sakeel-103 sir , please assign this to me.

**Comment by sakeel-103** [comment]
@Shariq2003 
Please remember, while making improvements, modifications, or any additional changes to the form, that it is a 'reactive form'.

**Comment by Shariq2003** [comment]
> @Shariq2003 Please remember, while making improvements, modifications, or any additional changes to the form, that it is a 'reactive form'.

Okay sir
