### ISSUE TITLE
Addition of All Contributors Photos in Readme.md File as a Token of Appreciation 

### ISSUE THREAD

**Issue by Shariq2003** [sakeel-103/DFS-BFS-Graph-Travers#75]
I want to add all the contributors photos in readme.md file to showcase a token of appreciation for their hard work.

![image](https://github.com/user-attachments/assets/bcb170ce-6cf8-4f21-bc16-fbc1cc6cac96)

Like this

**Comment by sakeel-103** [comment]
ok !!
