### ISSUE TITLE
Move logout button in profile dropdown menu

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#80]
- Move logout to profile dropdown menu for all pages

![c1](https://github.com/user-attachments/assets/b6e1004c-3330-492d-b681-b9fea94597bc)

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
And please add functionality as well in the logout button.

**Comment by mehul-m-prajapati** [comment]
picked up by someone https://github.com/sakeel-103/DFS-BFS-Graph-Travers/pull/115 
@sakeel-103

**Comment by sakeel-103** [comment]
Apologies for this, I didn't recognize it. Feel free, as I have assigned you the same level.
